USE SAKILA;

SELECT TITLE FROM FILM ORDER BY RELEASE_YEAR;

SELECT DISTINCT TITLE FROM FILM ORDER BY TITLE;

SELECT * FROM FILM
LIMIT 10;

SELECT * FROM FILM 
WHERE LENGTH<=90
ORDER BY REPLACEMENT_COST
LIMIT 10;

SELECT * FROM FILM
WHERE LENGHT<=100
ORDER BY REPLACEMENT_COST
LIMIT 10 OFFSET 20;

UPDATE FILM SET TITLE="ACADEMY DINOSAUR" WHERE FILM_ID =2;

SELECT * FROM  FILM;

DELETE FROM FILM WHERE film_id = 2;

TRUNCATE FILM;


